-- ============================================================================
-- EQEmu Item Tiering System - ALL TIERS (T1, T2, T3)
-- ============================================================================
-- Date: 2026-01-29
--
-- ID Offsets:
-- T1 (Enhanced): base_id + 300000
-- T2 (Exalted):  base_id + 500000
-- T3 (Ascendant): base_id + 700000
--
-- Strategy:
-- T1: Multiply existing stats, selectively inject 2-3 missing stats, NO premium stats
-- T2: Build on T1, multiply stats, RARELY add premium stats (~20%)
-- T3: Build on T2, multiply stats, COMMONLY add premium stats (~50%)
--
-- Premium stats: accuracy, attack, strikethrough, avoidance, stun resist, heroics, regen
-- ============================================================================

SET @start_time = NOW();
SET SESSION sql_mode = '';

-- Set generation run ID for this execution
SET @generation_run_id = CONCAT('run_', DATE_FORMAT(NOW(), '%Y%m%d_%H%i%s'));

SELECT '============================================================================' AS '';
SELECT CONCAT('GENERATING ALL TIERS - Run ID: ', @generation_run_id) AS '';
SELECT '============================================================================' AS '';

-- ============================================================================
-- TIER 1 (Enhanced) - Already generated by item_tier_generation_T1_SELECTIVE_FINAL.sql
-- ============================================================================
-- Run that script first, then run this script for T2 and T3

-- Verify T1 exists
SELECT
    'T1 (Enhanced) Status' AS tier,
    COUNT(*) AS item_count
FROM item_tier_map
WHERE tier_code = 1;

-- ============================================================================
-- TIER 2 (Exalted) - Builds on T1
-- ============================================================================

SELECT '============================================================================' AS '';
SELECT 'GENERATING TIER 2 (Exalted) - Builds on T1...' AS '';
SELECT '============================================================================' AS '';

-- T2 multipliers: AC×1.27, HP/Mana/End×1.40, Stats×1.27, Damage×1.08
-- ID offset: +500000
-- Premium stats: RARE (~20% via MOD(id, 5) = 0)

-- Check for collisions
SET @collision_count_t2 = (
    SELECT COUNT(*)
    FROM items i
    JOIN item_tier_map itm ON itm.base_item_id = i.id AND itm.tier_code = 1
    WHERE EXISTS (SELECT 1 FROM items WHERE id = i.id + 500000)
);

SELECT IF(@collision_count_t2 = 0, '✓ No ID collisions for T2 (500K offset)', 1/0) AS collision_check;

-- Generate T2 gear (builds on T1 stats)
INSERT INTO items (
    id, minstatus, Name,
    aagi, ac, accuracy, acha, adex, aint, asta, astr, awis, attack,
    cr, dr, fr, mr, pr, svcorruption,
    hp, mana, endur, regen, manaregen, enduranceregen,
    shielding, spellshield, dotshielding,
    damage, delay, strikethrough, avoidance, stunresist,
    heroic_str, heroic_int, heroic_wis, heroic_agi, heroic_dex, heroic_sta, heroic_cha,
    heroic_pr, heroic_dr, heroic_fr, heroic_cr, heroic_mr, heroic_svcorrup,
    spelldmg, healamt, clairvoyance, backstabdmg,
    bagslots, bagwr, bagsize, bagtype,
    proceffect, clickeffect, worneffect, focuseffect, scrolleffect, bardeffect,
    haste,
    artifactflag, augrestrict,
    augslot1type, augslot1visible, augslot2type, augslot2visible,
    augslot3type, augslot3visible, augslot4type, augslot4visible,
    augslot5type, augslot5visible, augslot6type, augslot6visible,
    augtype, banedmgamt, banedmgraceamt, banedmgbody, banedmgrace,
    bardtype, bardvalue, book, casttime, casttime_, charmfile, charmfileid,
    classes, color, combateffects, extradmgskill, extradmgamt, price,
    damageshield, deity, augdistiller, clicktype, clicklevel2,
    elemdmgtype, elemdmgamt,
    factionamt1, factionamt2, factionamt3, factionamt4,
    factionmod1, factionmod2, factionmod3, factionmod4,
    filename, fvnodrop, clicklevel, icon, idfile,
    itemclass, itemtype, ldonprice, ldontheme, ldonsold, light, lore, loregroup,
    magic, material, herosforgemodel, maxcharges, nodrop, norent,
    pendingloreflag, procrate, races, `range`, reclevel, recskill, reqlevel,
    sellrate, size, skillmodtype, skillmodvalue, slots,
    summonedflag, tradeskills, favor, weight,
    UNK012, UNK013, benefitflag, UNK054, UNK059, booktype,
    recastdelay, recasttype, guildfavor, UNK123, UNK124, attuneable, nopet,
    updated, comment, UNK127, pointtype, potionbelt, potionbeltslots,
    stacksize, notransfer, stackable, UNK134, UNK137,
    proctype, proclevel2, proclevel, UNK142,
    worntype, wornlevel2, wornlevel, UNK147,
    focustype, focuslevel2, focuslevel, UNK152,
    scrolltype, scrolllevel2, scrolllevel, UNK157,
    serialized, verified, serialization, source, UNK033, lorefile, UNK014,
    skillmodmax, UNK060,
    augslot1unk2, augslot2unk2, augslot3unk2, augslot4unk2, augslot5unk2, augslot6unk2,
    UNK120, UNK121, questitemflag, UNK132,
    clickunk5, clickunk6, clickunk7,
    procunk1, procunk2, procunk3, procunk4, procunk6, procunk7,
    wornunk1, wornunk2, wornunk3, wornunk4, wornunk5, wornunk6, wornunk7,
    focusunk1, focusunk2, focusunk3, focusunk4, focusunk5, focusunk6, focusunk7,
    scrollunk1, scrollunk2, scrollunk3, scrollunk4, scrollunk5, scrollunk6, scrollunk7,
    UNK193, purity, evoitem, evoid, evolvinglevel, evomax,
    clickname, procname, wornname, focusname, scrollname, bardname,
    dsmitigation, created, elitematerial, ldonsellbackrate, scriptfileid,
    expendablearrow, powersourcecapacity, bardeffecttype, bardlevel2, bardlevel,
    bardunk1, bardunk2, bardunk3, bardunk4, bardunk5, bardunk7,
    UNK214, subtype, UNK220, UNK221, heirloom,
    UNK223, UNK224, UNK225, UNK226, UNK227, UNK228, UNK229, UNK230,
    UNK231, UNK232, UNK233, UNK234, placeable, UNK236, UNK237, UNK238,
    UNK239, UNK240, UNK241, epicitem
)
SELECT
    base.id + 500000 AS id,
    base.minstatus,
    CONCAT(REPLACE(REPLACE(t1.Name, CHAR(0x12), ''), ' (Enhanced)', ''), ' ', CHAR(0x1A), '(Exalted)', CHAR(0x12)) AS Name,
    -- Stats: Multiply T1 by 1.27/1.10 = 1.154 (net 27% from base)
    FLOOR(t1.aagi * 1.154) AS aagi,
    FLOOR(t1.ac * 1.154) AS ac,
    -- Accuracy: Multiply existing, OR inject +2-3 for melee (20% chance)
    GREATEST(FLOOR(t1.accuracy * 1.154),
        CASE WHEN t1.accuracy = 0 AND (base.classes & 49629) > 0 AND MOD(base.id, 5) = 0 THEN 2 ELSE 0 END) AS accuracy,
    FLOOR(t1.acha * 1.154) AS acha,
    FLOOR(t1.adex * 1.154) AS adex,
    FLOOR(t1.aint * 1.154) AS aint,
    FLOOR(t1.asta * 1.154) AS asta,
    FLOOR(t1.astr * 1.154) AS astr,
    FLOOR(t1.awis * 1.154) AS awis,
    -- Attack: Multiply existing, OR inject +3 for melee (20% chance)
    GREATEST(FLOOR(t1.attack * 1.154),
        CASE WHEN t1.attack = 0 AND (base.classes & 49629) > 0 AND MOD(base.id, 5) = 1 THEN 3 ELSE 0 END) AS attack,
    -- Resists: Multiply T1
    FLOOR(t1.cr * 1.154) AS cr,
    FLOOR(t1.dr * 1.154) AS dr,
    FLOOR(t1.fr * 1.154) AS fr,
    FLOOR(t1.mr * 1.154) AS mr,
    FLOOR(t1.pr * 1.154) AS pr,
    FLOOR(t1.svcorruption * 1.154) AS svcorruption,
    -- HP/Mana/Endur: Multiply T1 by 1.40/1.18 = 1.186 (net 40% from base)
    FLOOR(t1.hp * 1.186) AS hp,
    FLOOR(t1.mana * 1.186) AS mana,
    FLOOR(t1.endur * 1.186) AS endur,
    FLOOR(t1.regen * 1.186) AS regen,
    FLOOR(t1.manaregen * 1.186) AS manaregen,
    FLOOR(t1.enduranceregen * 1.186) AS enduranceregen,
    -- Shielding: Multiply existing
    FLOOR(t1.shielding * 1.154) AS shielding,
    FLOOR(t1.spellshield * 1.154) AS spellshield,
    FLOOR(t1.dotshielding * 1.154) AS dotshielding,
    -- Damage: +8% from T1 (min +2 from T1), delay FROZEN
    CASE
        WHEN t1.delay > 0 THEN GREATEST(t1.damage + FLOOR(t1.damage * 0.08), t1.damage + 2)
        ELSE t1.damage
    END AS damage,
    t1.delay,
    -- Strikethrough: Multiply existing, OR inject +1 for melee (20% chance)
    GREATEST(FLOOR(t1.strikethrough * 1.154),
        CASE WHEN t1.strikethrough = 0 AND (base.classes & 49629) > 0 AND MOD(base.id, 5) = 2 THEN 1 ELSE 0 END) AS strikethrough,
    -- Avoidance: Multiply existing, OR inject +1 for tanks (20% chance)
    GREATEST(FLOOR(t1.avoidance * 1.154),
        CASE WHEN t1.avoidance = 0 AND (base.classes & 21) > 0 AND MOD(base.id, 5) = 3 THEN 1 ELSE 0 END) AS avoidance,
    -- Stun Resist: Multiply existing, OR inject +2 for tanks (20% chance)
    GREATEST(FLOOR(t1.stunresist * 1.154),
        CASE WHEN t1.stunresist = 0 AND (base.classes & 21) > 0 AND MOD(base.id, 5) = 4 THEN 2 ELSE 0 END) AS stunresist,
    -- Heroics: Add +1 to primary stat from T1 (20% chance)
    t1.heroic_str + CASE WHEN (base.classes & 49629) > 0 AND MOD(base.id, 5) = 0 THEN 1 ELSE 0 END AS heroic_str,
    t1.heroic_int + CASE WHEN (base.classes & 15360) > 0 AND MOD(base.id, 5) = 0 THEN 1 ELSE 0 END AS heroic_int,
    t1.heroic_wis + CASE WHEN (base.classes & 546) > 0 AND MOD(base.id, 5) = 0 THEN 1 ELSE 0 END AS heroic_wis,
    t1.heroic_agi AS heroic_agi,
    t1.heroic_dex AS heroic_dex,
    t1.heroic_sta + CASE WHEN (base.classes & 21) > 0 AND MOD(base.id, 5) = 0 THEN 1 ELSE 0 END AS heroic_sta,
    t1.heroic_cha AS heroic_cha,
    t1.heroic_pr, t1.heroic_dr, t1.heroic_fr, t1.heroic_cr, t1.heroic_mr, t1.heroic_svcorrup,
    -- Spell damage: unchanged at T2
    0, 0, 0, 0,
    -- Bags: zero for gear
    0, 0, 0, 0,
    -- Copy all other fields from T1
    t1.proceffect, t1.clickeffect, t1.worneffect, t1.focuseffect, t1.scrolleffect, t1.bardeffect,
    t1.haste,
    t1.artifactflag, t1.augrestrict,
    t1.augslot1type, t1.augslot1visible, t1.augslot2type, t1.augslot2visible,
    t1.augslot3type, t1.augslot3visible, t1.augslot4type, t1.augslot4visible,
    t1.augslot5type, t1.augslot5visible, t1.augslot6type, t1.augslot6visible,
    t1.augtype, t1.banedmgamt, t1.banedmgraceamt, t1.banedmgbody, t1.banedmgrace,
    t1.bardtype, t1.bardvalue, t1.book, t1.casttime, t1.casttime_, t1.charmfile, t1.charmfileid,
    t1.classes, t1.color, t1.combateffects, t1.extradmgskill, t1.extradmgamt, t1.price,
    t1.damageshield, t1.deity, t1.augdistiller, t1.clicktype, t1.clicklevel2,
    t1.elemdmgtype, t1.elemdmgamt,
    t1.factionamt1, t1.factionamt2, t1.factionamt3, t1.factionamt4,
    t1.factionmod1, t1.factionmod2, t1.factionmod3, t1.factionmod4,
    t1.filename, t1.fvnodrop, t1.clicklevel, t1.icon, t1.idfile,
    t1.itemclass, t1.itemtype, t1.ldonprice, t1.ldontheme, t1.ldonsold, t1.light, t1.lore, t1.loregroup,
    t1.magic, t1.material, t1.herosforgemodel, t1.maxcharges, t1.nodrop, t1.norent,
    t1.pendingloreflag, t1.procrate, t1.races, t1.`range`, t1.reclevel, t1.recskill, t1.reqlevel,
    t1.sellrate, t1.size, t1.skillmodtype, t1.skillmodvalue, t1.slots,
    t1.summonedflag, t1.tradeskills, t1.favor, t1.weight,
    t1.UNK012, t1.UNK013, t1.benefitflag, t1.UNK054, t1.UNK059, t1.booktype,
    t1.recastdelay, t1.recasttype, t1.guildfavor, t1.UNK123, t1.UNK124, t1.attuneable, t1.nopet,
    NOW() AS updated,
    CONCAT('T2 Exalted variant of item ', base.id, ' - ', @generation_run_id) AS comment,
    t1.UNK127, t1.pointtype, t1.potionbelt, t1.potionbeltslots,
    t1.stacksize, t1.notransfer, t1.stackable, t1.UNK134, t1.UNK137,
    t1.proctype, t1.proclevel2, t1.proclevel, t1.UNK142,
    t1.worntype, t1.wornlevel2, t1.wornlevel, t1.UNK147,
    t1.focustype, t1.focuslevel2, t1.focuslevel, t1.UNK152,
    t1.scrolltype, t1.scrolllevel2, t1.scrolllevel, t1.UNK157,
    t1.serialized, t1.verified, t1.serialization, t1.source, t1.UNK033, t1.lorefile, t1.UNK014,
    t1.skillmodmax, t1.UNK060,
    t1.augslot1unk2, t1.augslot2unk2, t1.augslot3unk2, t1.augslot4unk2, t1.augslot5unk2, t1.augslot6unk2,
    t1.UNK120, t1.UNK121, t1.questitemflag, t1.UNK132,
    t1.clickunk5, t1.clickunk6, t1.clickunk7,
    t1.procunk1, t1.procunk2, t1.procunk3, t1.procunk4, t1.procunk6, t1.procunk7,
    t1.wornunk1, t1.wornunk2, t1.wornunk3, t1.wornunk4, t1.wornunk5, t1.wornunk6, t1.wornunk7,
    t1.focusunk1, t1.focusunk2, t1.focusunk3, t1.focusunk4, t1.focusunk5, t1.focusunk6, t1.focusunk7,
    t1.scrollunk1, t1.scrollunk2, t1.scrollunk3, t1.scrollunk4, t1.scrollunk5, t1.scrollunk6, t1.scrollunk7,
    t1.UNK193, t1.purity, t1.evoitem, t1.evoid, t1.evolvinglevel, t1.evomax,
    t1.clickname, t1.procname, t1.wornname, t1.focusname, t1.scrollname, t1.bardname,
    t1.dsmitigation, t1.created, t1.elitematerial, t1.ldonsellbackrate, t1.scriptfileid,
    t1.expendablearrow, t1.powersourcecapacity, t1.bardeffecttype, t1.bardlevel2, t1.bardlevel,
    t1.bardunk1, t1.bardunk2, t1.bardunk3, t1.bardunk4, t1.bardunk5, t1.bardunk7,
    t1.UNK214, t1.subtype, t1.UNK220, t1.UNK221, t1.heirloom,
    t1.UNK223, t1.UNK224, t1.UNK225, t1.UNK226, t1.UNK227, t1.UNK228, t1.UNK229, t1.UNK230,
    t1.UNK231, t1.UNK232, t1.UNK233, t1.UNK234, t1.placeable, t1.UNK236, t1.UNK237, t1.UNK238,
    t1.UNK239, t1.UNK240, t1.UNK241, t1.epicitem
FROM items base
JOIN item_tier_map itm ON itm.base_item_id = base.id AND itm.tier_code = 1 AND itm.item_category = 'gear'
JOIN items t1 ON t1.id = itm.variant_item_id
WHERE NOT EXISTS (SELECT 1 FROM item_tier_map WHERE base_item_id = base.id AND tier_code = 2)
AND NOT EXISTS (SELECT 1 FROM items WHERE id = base.id + 500000);

SELECT CONCAT('✓ T2 gear generated: ', ROW_COUNT(), ' items') AS status;

-- Record T2 mappings
INSERT INTO item_tier_map (base_item_id, tier_code, variant_item_id, power_score, item_category, generation_run_id)
SELECT
    base.id,
    2,
    base.id + 500000,
    itm.power_score * 1.27,
    'gear',
    @generation_run_id
FROM items base
JOIN item_tier_map itm ON itm.base_item_id = base.id AND itm.tier_code = 1 AND itm.item_category = 'gear'
WHERE EXISTS (SELECT 1 FROM items WHERE id = base.id + 500000);

SELECT CONCAT('✓ T2 mappings recorded: ', ROW_COUNT()) AS status;

-- ============================================================================
-- TIER 3 (Ascendant) - Builds on T2
-- ============================================================================

SELECT '============================================================================' AS '';
SELECT 'GENERATING TIER 3 (Ascendant) - Builds on T2...' AS '';
SELECT '============================================================================' AS '';

-- T3 multipliers: AC×1.45, HP/Mana/End×1.70, Stats×1.45, Damage×1.15
-- ID offset: +700000
-- Premium stats: COMMON (~50% via MOD(id, 2) = 0)

-- Check for collisions
SET @collision_count_t3 = (
    SELECT COUNT(*)
    FROM items i
    JOIN item_tier_map itm ON itm.base_item_id = i.id AND itm.tier_code = 2
    WHERE EXISTS (SELECT 1 FROM items WHERE id = i.id + 700000)
);

SELECT IF(@collision_count_t3 = 0, '✓ No ID collisions for T3 (700K offset)', 1/0) AS collision_check;

-- Generate T3 gear (builds on T2 stats)
INSERT INTO items (
    id, minstatus, Name,
    aagi, ac, accuracy, acha, adex, aint, asta, astr, awis, attack,
    cr, dr, fr, mr, pr, svcorruption,
    hp, mana, endur, regen, manaregen, enduranceregen,
    shielding, spellshield, dotshielding,
    damage, delay, strikethrough, avoidance, stunresist,
    heroic_str, heroic_int, heroic_wis, heroic_agi, heroic_dex, heroic_sta, heroic_cha,
    heroic_pr, heroic_dr, heroic_fr, heroic_cr, heroic_mr, heroic_svcorrup,
    spelldmg, healamt, clairvoyance, backstabdmg,
    bagslots, bagwr, bagsize, bagtype,
    proceffect, clickeffect, worneffect, focuseffect, scrolleffect, bardeffect,
    haste,
    artifactflag, augrestrict,
    augslot1type, augslot1visible, augslot2type, augslot2visible,
    augslot3type, augslot3visible, augslot4type, augslot4visible,
    augslot5type, augslot5visible, augslot6type, augslot6visible,
    augtype, banedmgamt, banedmgraceamt, banedmgbody, banedmgrace,
    bardtype, bardvalue, book, casttime, casttime_, charmfile, charmfileid,
    classes, color, combateffects, extradmgskill, extradmgamt, price,
    damageshield, deity, augdistiller, clicktype, clicklevel2,
    elemdmgtype, elemdmgamt,
    factionamt1, factionamt2, factionamt3, factionamt4,
    factionmod1, factionmod2, factionmod3, factionmod4,
    filename, fvnodrop, clicklevel, icon, idfile,
    itemclass, itemtype, ldonprice, ldontheme, ldonsold, light, lore, loregroup,
    magic, material, herosforgemodel, maxcharges, nodrop, norent,
    pendingloreflag, procrate, races, `range`, reclevel, recskill, reqlevel,
    sellrate, size, skillmodtype, skillmodvalue, slots,
    summonedflag, tradeskills, favor, weight,
    UNK012, UNK013, benefitflag, UNK054, UNK059, booktype,
    recastdelay, recasttype, guildfavor, UNK123, UNK124, attuneable, nopet,
    updated, comment, UNK127, pointtype, potionbelt, potionbeltslots,
    stacksize, notransfer, stackable, UNK134, UNK137,
    proctype, proclevel2, proclevel, UNK142,
    worntype, wornlevel2, wornlevel, UNK147,
    focustype, focuslevel2, focuslevel, UNK152,
    scrolltype, scrolllevel2, scrolllevel, UNK157,
    serialized, verified, serialization, source, UNK033, lorefile, UNK014,
    skillmodmax, UNK060,
    augslot1unk2, augslot2unk2, augslot3unk2, augslot4unk2, augslot5unk2, augslot6unk2,
    UNK120, UNK121, questitemflag, UNK132,
    clickunk5, clickunk6, clickunk7,
    procunk1, procunk2, procunk3, procunk4, procunk6, procunk7,
    wornunk1, wornunk2, wornunk3, wornunk4, wornunk5, wornunk6, wornunk7,
    focusunk1, focusunk2, focusunk3, focusunk4, focusunk5, focusunk6, focusunk7,
    scrollunk1, scrollunk2, scrollunk3, scrollunk4, scrollunk5, scrollunk6, scrollunk7,
    UNK193, purity, evoitem, evoid, evolvinglevel, evomax,
    clickname, procname, wornname, focusname, scrollname, bardname,
    dsmitigation, created, elitematerial, ldonsellbackrate, scriptfileid,
    expendablearrow, powersourcecapacity, bardeffecttype, bardlevel2, bardlevel,
    bardunk1, bardunk2, bardunk3, bardunk4, bardunk5, bardunk7,
    UNK214, subtype, UNK220, UNK221, heirloom,
    UNK223, UNK224, UNK225, UNK226, UNK227, UNK228, UNK229, UNK230,
    UNK231, UNK232, UNK233, UNK234, placeable, UNK236, UNK237, UNK238,
    UNK239, UNK240, UNK241, epicitem
)
SELECT
    base.id + 700000 AS id,
    base.minstatus,
    CONCAT(REPLACE(REPLACE(t2.Name, CHAR(0x1A), ''), REPLACE(CHAR(0x12), '', ''), ' (Exalted)', ''), ' ', CHAR(0x0A), '(Ascendant)', CHAR(0x12)) AS Name,
    -- Stats: Multiply T2 by 1.45/1.27 = 1.142 (net 45% from base)
    FLOOR(t2.aagi * 1.142) AS aagi,
    FLOOR(t2.ac * 1.142) AS ac,
    -- Accuracy: Multiply existing, OR inject +4-5 for melee (50% chance)
    GREATEST(FLOOR(t2.accuracy * 1.142),
        CASE WHEN t2.accuracy = 0 AND (base.classes & 49629) > 0 AND MOD(base.id, 2) = 0 THEN 4 ELSE 0 END) AS accuracy,
    FLOOR(t2.acha * 1.142) AS acha,
    FLOOR(t2.adex * 1.142) AS adex,
    FLOOR(t2.aint * 1.142) AS aint,
    FLOOR(t2.asta * 1.142) AS asta,
    FLOOR(t2.astr * 1.142) AS astr,
    FLOOR(t2.awis * 1.142) AS awis,
    -- Attack: Multiply existing, OR inject +5 for melee (50% chance)
    GREATEST(FLOOR(t2.attack * 1.142),
        CASE WHEN t2.attack = 0 AND (base.classes & 49629) > 0 AND MOD(base.id, 2) = 1 THEN 5 ELSE 0 END) AS attack,
    -- Resists: Multiply T2
    FLOOR(t2.cr * 1.142) AS cr,
    FLOOR(t2.dr * 1.142) AS dr,
    FLOOR(t2.fr * 1.142) AS fr,
    FLOOR(t2.mr * 1.142) AS mr,
    FLOOR(t2.pr * 1.142) AS pr,
    FLOOR(t2.svcorruption * 1.142) AS svcorruption,
    -- HP/Mana/Endur: Multiply T2 by 1.70/1.40 = 1.214 (net 70% from base)
    FLOOR(t2.hp * 1.214) AS hp,
    FLOOR(t2.mana * 1.214) AS mana,
    FLOOR(t2.endur * 1.214) AS endur,
    -- Regen: Inject +1 for tanks/melee (10% chance via MOD(id, 10) = 0)
    GREATEST(FLOOR(t2.regen * 1.214),
        CASE WHEN t2.regen = 0 AND (base.classes & 49629) > 0 AND MOD(base.id, 10) = 0 THEN 1 ELSE 0 END) AS regen,
    -- Mana Regen: Inject +1 for casters (10% chance)
    GREATEST(FLOOR(t2.manaregen * 1.214),
        CASE WHEN t2.manaregen = 0 AND (base.classes & 15906) > 0 AND MOD(base.id, 10) = 0 THEN 1 ELSE 0 END) AS manaregen,
    FLOOR(t2.enduranceregen * 1.214) AS enduranceregen,
    -- Shielding: Multiply existing, OR inject +1 for tanks (50% chance)
    GREATEST(FLOOR(t2.shielding * 1.142),
        CASE WHEN t2.shielding = 0 AND (base.classes & 21) > 0 AND MOD(base.id, 2) = 0 THEN 1 ELSE 0 END) AS shielding,
    -- Spell Shield: Multiply existing, OR inject +2 for casters (50% chance)
    GREATEST(FLOOR(t2.spellshield * 1.142),
        CASE WHEN t2.spellshield = 0 AND (base.classes & 15906) > 0 AND MOD(base.id, 2) = 0 THEN 2 ELSE 0 END) AS spellshield,
    FLOOR(t2.dotshielding * 1.142) AS dotshielding,
    -- Damage: +12% from T2 (min +3 from T2), delay FROZEN
    CASE
        WHEN t2.delay > 0 THEN GREATEST(t2.damage + FLOOR(t2.damage * 0.12), t2.damage + 3)
        ELSE t2.damage
    END AS damage,
    t2.delay,
    -- Strikethrough: Multiply existing, OR inject +2 for melee (50% chance)
    GREATEST(FLOOR(t2.strikethrough * 1.142),
        CASE WHEN t2.strikethrough = 0 AND (base.classes & 49629) > 0 AND MOD(base.id, 2) = 0 THEN 2 ELSE 0 END) AS strikethrough,
    -- Avoidance: Multiply existing, OR inject +2 for tanks (50% chance)
    GREATEST(FLOOR(t2.avoidance * 1.142),
        CASE WHEN t2.avoidance = 0 AND (base.classes & 21) > 0 AND MOD(base.id, 2) = 0 THEN 2 ELSE 0 END) AS avoidance,
    -- Stun Resist: Multiply existing, OR inject +3 for tanks (50% chance)
    GREATEST(FLOOR(t2.stunresist * 1.142),
        CASE WHEN t2.stunresist = 0 AND (base.classes & 21) > 0 AND MOD(base.id, 2) = 0 THEN 3 ELSE 0 END) AS stunresist,
    -- Heroics: Add +2 to primary, +1 to secondary from T2 (50% chance)
    CASE WHEN (base.classes & 49629) > 0 AND MOD(base.id, 2) = 0 THEN t2.heroic_str + 2 ELSE t2.heroic_str END AS heroic_str,
    CASE WHEN (base.classes & 15360) > 0 AND MOD(base.id, 2) = 0 THEN t2.heroic_int + 2 ELSE t2.heroic_int END AS heroic_int,
    CASE WHEN (base.classes & 546) > 0 AND MOD(base.id, 2) = 0 THEN t2.heroic_wis + 2 ELSE t2.heroic_wis END AS heroic_wis,
    t2.heroic_agi + CASE WHEN (base.classes & 49608) > 0 AND MOD(base.id, 2) = 0 THEN 1 ELSE 0 END AS heroic_agi,
    t2.heroic_dex + CASE WHEN (base.classes & 49608) > 0 AND MOD(base.id, 2) = 0 THEN 1 ELSE 0 END AS heroic_dex,
    CASE WHEN (base.classes & 21) > 0 AND MOD(base.id, 2) = 0 THEN t2.heroic_sta + 2 ELSE t2.heroic_sta END AS heroic_sta,
    t2.heroic_cha AS heroic_cha,
    t2.heroic_pr, t2.heroic_dr, t2.heroic_fr, t2.heroic_cr, t2.heroic_mr, t2.heroic_svcorrup,
    -- Spell damage: Inject +5 for INT casters (50% chance)
    CASE WHEN (base.classes & 15360) > 0 AND MOD(base.id, 2) = 0 THEN 5 ELSE 0 END AS spelldmg,
    -- Heal amt: Inject +5 for WIS casters (50% chance)
    CASE WHEN (base.classes & 546) > 0 AND MOD(base.id, 2) = 0 THEN 5 ELSE 0 END AS healamt,
    0 AS clairvoyance,
    0 AS backstabdmg,
    -- Bags: zero for gear
    0, 0, 0, 0,
    -- Copy all other fields from T2
    t2.proceffect, t2.clickeffect, t2.worneffect, t2.focuseffect, t2.scrolleffect, t2.bardeffect,
    t2.haste,
    t2.artifactflag, t2.augrestrict,
    t2.augslot1type, t2.augslot1visible, t2.augslot2type, t2.augslot2visible,
    t2.augslot3type, t2.augslot3visible, t2.augslot4type, t2.augslot4visible,
    t2.augslot5type, t2.augslot5visible, t2.augslot6type, t2.augslot6visible,
    t2.augtype, t2.banedmgamt, t2.banedmgraceamt, t2.banedmgbody, t2.banedmgrace,
    t2.bardtype, t2.bardvalue, t2.book, t2.casttime, t2.casttime_, t2.charmfile, t2.charmfileid,
    t2.classes, t2.color, t2.combateffects, t2.extradmgskill, t2.extradmgamt, t2.price,
    t2.damageshield, t2.deity, t2.augdistiller, t2.clicktype, t2.clicklevel2,
    t2.elemdmgtype, t2.elemdmgamt,
    t2.factionamt1, t2.factionamt2, t2.factionamt3, t2.factionamt4,
    t2.factionmod1, t2.factionmod2, t2.factionmod3, t2.factionmod4,
    t2.filename, t2.fvnodrop, t2.clicklevel, t2.icon, t2.idfile,
    t2.itemclass, t2.itemtype, t2.ldonprice, t2.ldontheme, t2.ldonsold, t2.light, t2.lore, t2.loregroup,
    t2.magic, t2.material, t2.herosforgemodel, t2.maxcharges, t2.nodrop, t2.norent,
    t2.pendingloreflag, t2.procrate, t2.races, t2.`range`, t2.reclevel, t2.recskill, t2.reqlevel,
    t2.sellrate, t2.size, t2.skillmodtype, t2.skillmodvalue, t2.slots,
    t2.summonedflag, t2.tradeskills, t2.favor, t2.weight,
    t2.UNK012, t2.UNK013, t2.benefitflag, t2.UNK054, t2.UNK059, t2.booktype,
    t2.recastdelay, t2.recasttype, t2.guildfavor, t2.UNK123, t2.UNK124, t2.attuneable, t2.nopet,
    NOW() AS updated,
    CONCAT('T3 Ascendant variant of item ', base.id, ' - ', @generation_run_id) AS comment,
    t2.UNK127, t2.pointtype, t2.potionbelt, t2.potionbeltslots,
    t2.stacksize, t2.notransfer, t2.stackable, t2.UNK134, t2.UNK137,
    t2.proctype, t2.proclevel2, t2.proclevel, t2.UNK142,
    t2.worntype, t2.wornlevel2, t2.wornlevel, t2.UNK147,
    t2.focustype, t2.focuslevel2, t2.focuslevel, t2.UNK152,
    t2.scrolltype, t2.scrolllevel2, t2.scrolllevel, t2.UNK157,
    t2.serialized, t2.verified, t2.serialization, t2.source, t2.UNK033, t2.lorefile, t2.UNK014,
    t2.skillmodmax, t2.UNK060,
    t2.augslot1unk2, t2.augslot2unk2, t2.augslot3unk2, t2.augslot4unk2, t2.augslot5unk2, t2.augslot6unk2,
    t2.UNK120, t2.UNK121, t2.questitemflag, t2.UNK132,
    t2.clickunk5, t2.clickunk6, t2.clickunk7,
    t2.procunk1, t2.procunk2, t2.procunk3, t2.procunk4, t2.procunk6, t2.procunk7,
    t2.wornunk1, t2.wornunk2, t2.wornunk3, t2.wornunk4, t2.wornunk5, t2.wornunk6, t2.wornunk7,
    t2.focusunk1, t2.focusunk2, t2.focusunk3, t2.focusunk4, t2.focusunk5, t2.focusunk6, t2.focusunk7,
    t2.scrollunk1, t2.scrollunk2, t2.scrollunk3, t2.scrollunk4, t2.scrollunk5, t2.scrollunk6, t2.scrollunk7,
    t2.UNK193, t2.purity, t2.evoitem, t2.evoid, t2.evolvinglevel, t2.evomax,
    t2.clickname, t2.procname, t2.wornname, t2.focusname, t2.scrollname, t2.bardname,
    t2.dsmitigation, t2.created, t2.elitematerial, t2.ldonsellbackrate, t2.scriptfileid,
    t2.expendablearrow, t2.powersourcecapacity, t2.bardeffecttype, t2.bardlevel2, t2.bardlevel,
    t2.bardunk1, t2.bardunk2, t2.bardunk3, t2.bardunk4, t2.bardunk5, t2.bardunk7,
    t2.UNK214, t2.subtype, t2.UNK220, t2.UNK221, t2.heirloom,
    t2.UNK223, t2.UNK224, t2.UNK225, t2.UNK226, t2.UNK227, t2.UNK228, t2.UNK229, t2.UNK230,
    t2.UNK231, t2.UNK232, t2.UNK233, t2.UNK234, t2.placeable, t2.UNK236, t2.UNK237, t2.UNK238,
    t2.UNK239, t2.UNK240, t2.UNK241, t2.epicitem
FROM items base
JOIN item_tier_map itm ON itm.base_item_id = base.id AND itm.tier_code = 2 AND itm.item_category = 'gear'
JOIN items t2 ON t2.id = itm.variant_item_id
WHERE NOT EXISTS (SELECT 1 FROM item_tier_map WHERE base_item_id = base.id AND tier_code = 3)
AND NOT EXISTS (SELECT 1 FROM items WHERE id = base.id + 700000);

SELECT CONCAT('✓ T3 gear generated: ', ROW_COUNT(), ' items') AS status;

-- Record T3 mappings
INSERT INTO item_tier_map (base_item_id, tier_code, variant_item_id, power_score, item_category, generation_run_id)
SELECT
    base.id,
    3,
    base.id + 700000,
    itm.power_score * 1.45,
    'gear',
    @generation_run_id
FROM items base
JOIN item_tier_map itm ON itm.base_item_id = base.id AND itm.tier_code = 2 AND itm.item_category = 'gear'
WHERE EXISTS (SELECT 1 FROM items WHERE id = base.id + 700000);

SELECT CONCAT('✓ T3 mappings recorded: ', ROW_COUNT()) AS status;

-- ============================================================================
-- SUMMARY
-- ============================================================================

SELECT '============================================================================' AS '';
SELECT 'ALL TIERS GENERATION COMPLETE!' AS '';
SELECT '============================================================================' AS '';

SELECT
    tier_code,
    CASE tier_code
        WHEN 1 THEN 'Enhanced (T1)'
        WHEN 2 THEN 'Exalted (T2)'
        WHEN 3 THEN 'Ascendant (T3)'
    END AS tier_name,
    COUNT(*) AS item_count,
    item_category
FROM item_tier_map
WHERE generation_run_id = @generation_run_id
GROUP BY tier_code, item_category
ORDER BY tier_code, item_category;

SELECT CONCAT('✓ Total execution time: ', TIMESTAMPDIFF(SECOND, @start_time, NOW()), ' seconds') AS timing;
